name: furniture
description: https://www.figmacrush.com/furniture-free-figma-mobile-ui-kit/

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.2.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  # assets
  assets:
   - assets/
   - assets/registration/
